### PR TITLE
Change to the latest container

### PR DESCRIPTION
**Pull request by sofstam**

### CODE REVIEW

**Review by ljmesi — APPROVED** [review]
Looks good to me. I guess it's good to have this before getting the final gms dockerhub and possible sylabs cloud implementation is up and running.

**Comment by ljmesi** [comment]
I realised that actually [this](https://github.com/genomic-medicine-sweden/gmsmetapost/blob/4af9b7305aef60d926e2e3c62b3c49fd80f9cf41/.github/workflows/docker-image.yml#L37) is not now pushing to right dockerhub location but maybe that is not so crucial?

**Comment by ljmesi** [comment]
[These](https://github.com/genomic-medicine-sweden/gmsmetapost/blob/26bd99271819e1a3172d602dbc2a7abcd394eaf8/.github/workflows/docker-image.yml#L28-L29) should also be changed so that the pushing to dockerhub works. But maybe you could consider adding your own credentials as secrets and use them?

**Comment by sofstam** [comment]
Right, lets leave it as it is then for now. I am changing it back!

**Comment by ljmesi** [comment]
Ok.

**Review by ljmesi — APPROVED** [review]

**Comment by sofstam** [comment]
I have now adressed all the comments above.

**Review by ljmesi — APPROVED** [review]
Looks good to me.

**Pull request merged**
